controller_frequency: 20.0
ChannelController:
  safe_waypoint_channel_width: 0.65
  safe_channel_width: 0.5

  channel_score_da: 1.0
  channel_score_dist: 0.3

  max_channel_length: 3.0

  min_get_to_safe_dist_time: 7.0
  max_get_to_safe_dist_time: 20.0
  waypoint_reached_dist: 0.6
  waypoint_reached_angle: 7.0

  goal_reached_dist: 0.15
  goal_reached_angle: 0.17

# TODO measure this
  min_tv: 0.08
# Actual robot max is probably 2.4 m/s
# Stay slightly lower to allow rotational control
  max_tv: 2.0
  min_rv: 0.0
# 90 deg/s. Actual robot can go 180 deg/s, but we don't want that craziness
  max_rv: 1.6
# TODO measure this (floor dependent)
  min_inplace_rv: 0.5

  stopped_tv: 0.05
  stopped_rv: 0.1

# Takes about 2 - 2.5 s to reach speed of 2.4 m/s
# Competition maybe try 1 - 1.2 for max strain
  max_accel_tv: 0.8
# Braking accel is much higher about -2.9 max. Don't force this too often for strain
  max_accel_rv: -1.0

  wait_for_obstacles_time: 15.0
  no_progress_hard_clear_time: 60.0

  visualize_voronoi: true

