controller_frequency: 20.0
ChannelController:
  safe_waypoint_channel_width: 0.65
  safe_channel_width: 0.5

  channel_score_da: 1.0
  channel_score_dist: 0.3

  max_channel_length: 3.0

  min_get_to_safe_dist_time: 7.0
  max_get_to_safe_dist_time: 20.0
  waypoint_reached_dist: 0.6
  waypoint_reached_angle: 7.0

  goal_reached_dist: 0.15
  goal_reached_angle: 0.17

  min_tv: 0.08
  max_tv: 0.5
  min_rv: 0.0
  max_rv: 1.6
  min_inplace_rv: 0.5

  stopped_tv: 0.05
  stopped_rv: 0.1

  max_accel_tv: 1.0
  max_accel_rv: -1.0

  wait_for_obstacles_time: 15.0
  no_progress_hard_clear_time: 60.0

  visualize_voronoi: true

