#map_type: voxel
map_type: costmap
#z_resolution: 0.05
#z_voxels: 16
#publish_voxel_map: true
#unknown_threshold: 16
max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot
obstacle_range: 2.0
raytrace_range: 3.0
robot_radius: 0.20
inflation_radius: 0.30
observation_sources: base_scan #map_cloud kinect bump

base_scan: {data_type: LaserScan, topic: /base_scan_filtered, marking: true, clearing: true, observation_persistence: 1.0}

#kinect: {data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true, min_obstacle_height: 0.1, max_obstacle_height: 0.6, observation_persistence: 0.1}

#map_cloud: {data_type: PointCloud2, topic: /obstacle_cloud, marking: true, clearing: false}

# Current bump cloud configuration
#bump: {data_type: PointCloud2, topic: mobile_base/sensors/bumper_pointcloud, marking: true, clearing: false}

# These were for the create, but I think weren't getting used. 
# Can we merge to a common configuration - DJS?
# scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
# left_bump: {data_type: PointCloud2, topic: /bump_sensor_left, marking: true, clearing: true}
# right_bump: {data_type: PointCloud2, topic: /bump_sensor_right, marking: true, clearing: true}
