local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 20.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 8.0
   height: 8.0
   resolution: 0.075
   transform_tolerance: 0.5

