number_banner_0:
  #active_support: 10.0
  #inactive_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.8, 0.4, 0.0]
number_banner_1:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.8, 0.8, 0.0]
number_banner_2:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.4, 0.8, 0.0]
number_banner_3:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.0, 0.8, 0.0]
number_banner_4:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.0, 0.8, 0.4]
number_banner_5:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.0, 0.8, 0.8]
number_banner_6:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.0, 0.4, 0.8]
number_banner_7:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.0, 0.0, 0.8]
number_banner_8:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.4, 0.0, 0.8]
number_banner_9:
  active_support: 1.0
  min_height: 0.2
  max_height: 0.7
  marker_color: [0.8, 0.0, 0.8]
target_marker:
  active_support: 1.0
  min_height: 0.1
  max_height: 0.2
  marker_color: [0.8, 0.8, 0.8]
isolated_lines:
  active_support: 1.0
  min_height: -0.2
  max_height: 0.2
  marker_color: [0.8, 0.4, 0.8]
negative_update:
  - topic: axis215/camera_info
    min_distance: 2.0
    max_distance: 5.0
    #ignore_border_pixels: 10
    negative_support: 0.5
