optimal_exploration_distance: 1.5
approach_distance: 1.0
ring_distance: 0.3
max_loading_station_distance_from_center: 1.5
min_travel_distance_for_rescan: 1.0
cube_timeout: 15.0
move_base_timeout: 30.0
approach_timeout: 20.0
worldmodel_ageing_rate: 0.1
min_verified_support: 20
max_verified_support: 40
axis_pan: 0.0
axis_tilt: -0.3
axis_sweep_duration: 1.0
axis_sweep_angle: 0.3

estop_topics: ["/estop", "/joystick_estop"]
