optimal_exploration_distance: 3.0
min_verification_distance: 2.0
max_verification_distance: 5.0
max_verification_angle: 0.5235
verification_duration: 5.0
approach_distance: 1.0
approach_distance_tolerance: 1.5
approach_test_distance: 0.4
max_approach_angle: 0.5235
ring_distance: 0.25
max_loading_station_distance_from_center: 2.0
min_travel_distance_for_rescan: 3.0
cube_timeout: 15.0
move_base_timeout: 30.0
standstill_timeout: 30.0
approach_timeout: 20.0
worldmodel_ageing_rate: 0.1
min_valid_support: 5
min_trusted_support: 40
number_conflict_distance: 2.5
domination_factor: 2.0
axis_pan: 0.0
axis_tilt: -0.3
axis_sweep_duration: 2.0
axis_sweep_angle: 0.3
smart_loading_station_selection: true
hack_octa_loading_station: true
max_merge_distance: 1.4
random_loading_stations: true

estop_topics: ["/estop", "/joystick_estop"]
